export const siteOrigin = "https://florencia-frumento.web.app";

export const caseStudyCatalog = [
  {
    id: "amazon",
    href: "/casos/carrito-amazon.html",
    route: "/casos/carrito-amazon/",
    imageSrc: "/case-assets/case-preview-carrito-amazon.png",
    imageAlt: "{{ meta.ogImageAlt }}",
    imageType: "image/png",
    imageWidth: 888,
    imageHeight: 579,
    socialImageSrc: "/case-assets/social/carrito-amazon-social.jpg",
    socialImageType: "image/jpeg",
    socialImageWidth: 1200,
    socialImageHeight: 630,
    mediaClassName: "project-media-amazon",
    priority: "featured",
    tags: ["amazon", "featured", "research", "ux"]
  },
  {
    id: "banner-nubecommerce",
    href: "/casos/banner-nubecommerce.html",
    route: "/casos/banner-nubecommerce/",
    imageSrc: "/case-assets/case-preview-nubecommerce.jpg",
    imageAlt: "{{ meta.ogImageAlt }}",
    imageType: "image/jpeg",
    imageWidth: 1600,
    imageHeight: 1000,
    socialImageSrc: "/case-assets/social/banner-nubecommerce-social.jpg",
    socialImageType: "image/jpeg",
    socialImageWidth: 1200,
    socialImageHeight: 630,
    mediaClassName: "project-media-banner",
    priority: "featured",
    tags: ["tiendanube", "featured", "research", "product"]
  },
  {
    id: "cta-migrar-tienda",
    href: "/casos/cta-migrar-tienda.html",
    route: "/casos/cta-migrar-tienda/",
    imageSrc: "/case-assets/case-preview-cta-migrar-tienda.jpg",
    imageAlt: "{{ meta.ogImageAlt }}",
    imageType: "image/jpeg",
    imageWidth: 1600,
    imageHeight: 1000,
    socialImageSrc: "/case-assets/social/cta-migrar-tienda-social.jpg",
    socialImageType: "image/jpeg",
    socialImageWidth: 1200,
    socialImageHeight: 630,
    mediaClassName: "project-media-cta",
    priority: "featured",
    tags: ["tiendanube", "featured", "growth", "conversion"]
  },
  {
    id: "recursos-descargables",
    href: "/casos/recursos-descargables.html",
    route: "/casos/recursos-descargables/",
    imageSrc: "/case-assets/case-preview-recursos.jpg",
    imageAlt: "{{ meta.ogImageAlt }}",
    imageType: "image/jpeg",
    imageWidth: 1600,
    imageHeight: 1000,
    socialImageSrc: "/case-assets/social/recursos-descargables-social.jpg",
    socialImageType: "image/jpeg",
    socialImageWidth: 1200,
    socialImageHeight: 630,
    mediaClassName: "project-media-resource",
    priority: "standard",
    tags: ["lead-generation", "seo", "content"]
  },
  {
    id: "ristretto",
    href: "/casos/ristretto.html",
    route: "/casos/ristretto/",
    imageSrc: "/case-assets/case-preview-ristretto.jpg",
    imageAlt: "{{ meta.ogImageAlt }}",
    imageType: "image/jpeg",
    imageWidth: 1500,
    imageHeight: 844,
    socialImageSrc: "/case-assets/social/ristretto-social.jpg",
    socialImageType: "image/jpeg",
    socialImageWidth: 1200,
    socialImageHeight: 630,
    mediaClassName: "project-media-ristretto",
    priority: "featured",
    tags: ["ristretto", "featured", "product", "ux"]
  }
];

export const caseStudies = caseStudyCatalog;
